site_name: Nyarch Linux Wiki
theme: material
repo_name: NyarchWiki
repo_url: https://github.com/NyarchLinux/NyarchWiki

nav:
    - 'index.md'
    - 'future_projects.md'
    - Installation:
         - 'installation.md'
         - 'nvidia.md'
         - 'nyarcher.md'
    - 'applications.md'
    - 'nyarchassistant.md'

theme:
  name: material 
  logo: assets/nyarch-logo.png
  favicon: assets/nyarch-logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.expand
  icon: 
    repo: fontawesome/brands/github 
  palette:
    - scheme: slate
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  homepage: "https://nyarchlinux.moe"
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/NyarchLinux
      name: Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/NyarchLinux/NyarchLinux
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xuw6BNXXE7
      name: Discord
copyright: Copyright &copy; 2024 Nyarch Linux
